### ISSUE TITLE
installation Issue by composer with PHP version 7.2.x

### ISSUE THREAD

**Issue by aboutzahurul** [helpcrunch/magento2-plugin#1]
Unable to install by composer on magento 2.3.1 because of php version 7.2.x. Can you please add support for php 7.2.x on composer.json

**Comment by fervallen** [comment]
Here you go

**Comment by aboutzahurul** [comment]
Hi @fervallen, now no php issue but still this module dont support magento 2.3.1
while trying to install by composer on magento 2.3.1 with php 7.2.x it show error like:

`- helpcrunch/magento2-module dev-master requires magento/framework 100.*`

Please add support for magento 2.3.1 on your composer.json

**Comment by fervallen** [comment]
I've changed it, but we didn't test it ith ^2.3.
